// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxjgsiseyrkjerecrpdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4amdzaXNleXJramVyZWNycGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTU1NTgsImV4cCI6MjA2OTkzMTU1OH0.bKfcX3VKFPUXR1iIWtStmMKJLYAkGOIWpakhT2vADZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});